package com.pfe.stb.notifications.model.enums;

public enum NotificationType {
  COMPANY_REQUEST_STATUS_CHANGED,
  FOUNDATION_DOCUMENT_UPLOADED,
  FOUNDATION_DOCUMENT_VALIDATED,
  FOUNDATION_DOCUMENT_REJECTED,
  USER_ONBOARDING_COMPLETED
}
